Repository FlaviusAugustus/TERMINAL, pull requests merged in 2025-06, with the labels that each got.

#73 Feature/complete sidebar
  Client/package-lock.json
  Client/package.json
  Client/src/App.tsx
  Client/src/components/Dashboard/EntityAmountCard.tsx
  Client/src/components/Navbar/Sidebar.tsx
  Client/src/components/Navbar/SidebarLinkGroup.tsx
  Client/src/components/Navbar/SidebarUserProfile.tsx
  Client/src/components/Navbar/TerminalSidebarContent.tsx
  Client/src/components/Shared/Table/TableCard.tsx
  Client/src/hooks/projects/useGetProjectAmount.ts
  Client/src/hooks/recipes/useGetRecipeAmount.ts
  Client/src/hooks/samples/useGetRecentSamples.ts
  Client/src/hooks/samples/useSampleAmount.ts
  Client/src/hooks/users/useLogout.ts
  Client/src/hooks/users/useUserAmount.ts
  Client/src/pages/DashboardPage.tsx
  Client/src/pages/LoginPage.tsx
  Client/src/pages/layouts/AuthorizedLayout.tsx
  Client/src/utils/toast.utils.tsx
  cert/_cert.pem
Labels: type:feature

#77 Add adding recipe name
  Client/src/components/AddRecipe/AddRecipeActions.tsx
  Client/src/components/AddRecipe/AddRecipeDialog.tsx
  Client/src/components/Settings/Users/Users.tsx
  Client/src/components/Shared/DialogComp.tsx
  Client/src/components/Shared/Forms/InputField.tsx
Labels: type:feature

#84 Feature/add sample dialog
  Client/src/App.tsx
  Client/src/components/AddRecipe/AddRecipeActions.tsx
  Client/src/components/AddRecipe/AddRecipeDialog.tsx
  Client/src/components/AddRecipe/StepTabList.tsx
  Client/src/components/AddSample/AddSampleDialog.tsx
  Client/src/components/Login/LoginForm.tsx
  Client/src/components/Projects/NewProjectForm.tsx
  Client/src/components/Register/RegisterForm.tsx
  Client/src/components/Settings/Users/InvitationForm.tsx
  Client/src/components/Shared/Forms/InputField.tsx
  Client/src/components/Shared/Forms/NewProjectForm.tsx
  Client/src/components/Shared/InputField.tsx
  Client/src/components/Shared/InputLabelAndValidation.tsx
  Client/src/components/Shared/LabeledCheckbox.tsx
  Client/src/components/Shared/LabeledSelect.tsx
  Client/src/components/Shared/SubmitButton.tsx
  Client/src/components/Shared/TerminalBanner.tsx
  Client/src/hooks/apiHooks.ts
  Client/src/hooks/projects/useAddProject.ts
Labels: type:feature

#87 Feature/users page
  Client/src/components/Navbar/MobileNavbar.tsx
  Client/src/components/Shared/Chip.tsx
  Client/src/components/Shared/DialogComp.tsx
  Client/src/components/Shared/IconButton.tsx
  Client/src/components/Shared/Table/TableManagment.tsx
  Client/src/components/Shared/Table/TableView.tsx
  Client/src/components/Users/UserDetails.tsx
  Client/src/components/Users/Users.tsx
  Client/src/components/Users/UsersRowActions.tsx
  Client/src/pages/UsersPage.tsx
  Client/src/pages/layouts/AuthorizedLayout.tsx
  Client/src/utils/colorUtils.tsx
Labels: type:feature

#88 Feature/samples page
  Client/src/api/models/Role.ts
  Client/src/components/Samples/SampleDetails.tsx
  Client/src/components/Samples/Samples.tsx
  Client/src/components/Samples/SamplesRowActions.tsx
  Client/src/components/Shared/Chip.tsx
  Client/src/components/Shared/DialogComp.tsx
  Client/src/components/Users/UserDetails.tsx
  Client/src/pages/DashboardPage.tsx
  Client/src/pages/SamplesPage.tsx
  Client/src/pages/UsersPage.tsx
Labels: type:feature

#92 Fix EF Core error after bumping to .NET 9
  Server/src/Terminal.Backend.Infrastructure/DAL/Extensions.cs
  Server/test/Terminal.Backend.Architecture/Terminal.Backend.Architecture.csproj
  Server/test/Terminal.Backend.Integration/Terminal.Backend.Integration.csproj
  Server/test/Terminal.Backend.Unit/Terminal.Backend.Unit.csproj
  compose.dev.yaml
  compose.yaml
Labels: type:bug

#93 Feature/pin
  Client/src/api/terminalSchemas.ts
  Client/src/components/Projects/ProjectDetails.tsx
  Client/src/components/Projects/Projects.tsx
  Client/src/components/Projects/ProjectsRowActions.tsx
  Client/src/components/Samples/Samples.tsx
  Client/src/components/Shared/Chip.tsx
  Client/src/components/Shared/Table/TableView.tsx
  Client/src/components/Users/Users.tsx
  Client/src/hooks/projects/useGetAllProjects.ts
  Client/src/pages/DashboardPage.tsx
  Client/src/pages/ProjectsPage.tsx
  Client/src/utils/colorUtils.tsx
  Server/src/Terminal.Backend.Application/DTO/Projects/GetProjectsDto.cs
  Server/src/Terminal.Backend.Infrastructure/DAL/Handlers/Extensions.cs
  Server/src/Terminal.Backend.Infrastructure/DAL/Handlers/Projects/SearchProjectQueryHandler.cs
Labels: type:feature

#94 Fix redirect to login when unauthorized
  Client/src/App.tsx
  Client/src/pages/LoginOrNotFound.tsx
Labels: type:bug

#116 Add workflow for bulding and pushing docker images
  .github/workflows/build-images.yml
Labels: type:infrastructure

#117 Build and push image
  .github/workflows/build-images.yml
Labels: type:infrastructure

#124 Redesign recipes page
  Client/src/components/Recipes/RecipeDetails.tsx
  Client/src/components/Recipes/Recipes.tsx
  Client/src/components/Recipes/RecipesRowActions.tsx
  Client/src/components/Samples/SampleDetails.tsx
  Client/src/components/Samples/Samples.tsx
  Client/src/components/Shared/Detail.tsx
  Client/src/components/Shared/StepDetails.tsx
  Client/src/components/Shared/Table/TableCard.tsx
  Client/src/components/Shared/Table/TableView.tsx
  Client/src/pages/RecipesPage.tsx
  Client/src/pages/SamplesPage.tsx
Labels: type:feature

#130 Fix layout issues
  Client/index.html
  Client/src/pages/layouts/AuthorizedLayout.tsx
  Client/src/pages/layouts/TableLayout.tsx
Labels: type:bug

#131 Fix overscroll and move html tag styles to index.css
  Client/index.html
  Client/src/index.css
Labels: type:bug

#127 Feature/parameters view
  Client/src/App.tsx
  Client/src/components/AddRecipe/ParameterSelect.tsx
  Client/src/components/Navbar/TerminalSidebarContent.tsx
  Client/src/components/Parameters/ParameterDetails.tsx
  Client/src/components/Parameters/Parameters.tsx
  Client/src/components/Projects/Projects.tsx
  Client/src/components/Projects/ProjectsRowActions.tsx
  Client/src/components/Recipes/Recipes.tsx
  Client/src/components/Recipes/RecipesRowActions.tsx
  Client/src/components/Samples/Samples.tsx
  Client/src/components/Samples/SamplesRowActions.tsx
  Client/src/components/Shared/Table/RowActions.tsx
  Client/src/hooks/parameters/useGetParameters.ts
  Client/src/hooks/useAddRecipeContext.tsx
  Client/src/hooks/useRecipeDragContext.tsx
  Client/src/hooks/useTableColumns.tsx
  Client/src/pages/AddRecipe.tsx
  Client/src/pages/ParametersPage.tsx
  Client/src/pages/ProjectsPage.tsx
Labels: type:feature

#134 Add fullscreen loader while loading user data
  Client/package-lock.json
  Client/package.json
  Client/src/components/Shared/FullScreenLoader.tsx
  Client/src/pages/layouts/AuthorizedLayout.tsx
  Client/src/tailwind.config.js
  Client/vite.config.ts
Labels: type:feature

#146 Feature/form validation
  Client/src/components/Login/LoginForm.tsx
  Client/src/components/Projects/NewProjectForm.tsx
  Client/src/components/Shared/Form.tsx
  Client/src/components/Shared/InputField.tsx
  Client/src/components/Shared/InputLabelAndValidation.tsx
  Client/src/components/Shared/LabeledSelect.tsx
Labels: type:feature

#148 Bugfix/refresh
  Client/src/api/apiClient.ts
  Client/src/components/Login/LoginForm.tsx
  Client/src/components/Shared/InputField.tsx
Labels: type:bug
